export const config = {
	ERROR: {
		AUTH: {
			UNAUTHORIZED: "Unauthorized",
			INVALID_TOKEN: "Invalid token",
			REGISTRATION_VALIDATION_FAILED: "Registration validation failed",
			LOGIN_VALIDATION_FAILED: "Login validation failed",
			PASSWORD_UPDATE_VALIDATION_FAILED: "Password update validation failed",
			FIRST_NAME_LAST_NAME_REQUIRED: "First name and last name are required",
			INVALID_ORGANIZATION_ID_FORMAT: "Invalid organization ID format",
			ORGANIZATION_NOT_FOUND: "Organization not found",
			USER_ALREADY_EXISTS: "User already exists",
			ERROR_DURING_REGISTRATION: "Error during registration",
			INVALID_CREDENTIALS: "Invalid credentials",
			ERROR_DURING_LOGIN: "Error during login",
			USER_ID_PASSWORD_REQUIRED: "User ID and new password are required",
			PASSWORD_MIN_LENGTH: "Password must be at least 6 characters long",
			ERROR_UPDATING_PASSWORD: "Error updating password",
			USER_NOT_FOUND: "User not found",
			FAILED_TO_CREATE_OR_FIND_PERSON: "Failed to create or find person",
		},
		TEMPLATE: {
			VALIDATION_FAILED: "Template validation failed",
			INVALID_ID_FORMAT: "Invalid template ID format",
			NOT_FOUND: "Template not found",
			CREATE_FAILED: "Error creating template",
			UPDATE_FAILED: "Error updating template",
			DELETE_FAILED: "Error deleting template",
			GET_FAILED: "Error getting template",
			GET_ALL_FAILED: "Error getting templates",
			ERROR_GETTING: "Error getting template",
			ERROR_UPDATING: "Error updating template",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		QUERY_PARAMS: {
			MISSING_ID: "ID parameter is required",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate must be a string",
			INVALID_PAGE: "Invalid page",
			INVALID_LIMIT: "Invalid limit",
			INVALID_ORDER: "Invalid order",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
			INVALID_SORT: "Invalid sort",
			SORT_MUST_BE_STRING: "Sort must be a string",
			INVALID_FILTER: "Invalid filter",
			FILTER_MUST_BE_STRING: "Filter must be a string",
			INVALID_QUERY: "Invalid query",
			QUERY_MUST_BE_STRING: "Query must be a string",
			INVALID_DOCUMENT: "Invalid document",
			DOCUMENT_MUST_BE_STRING: "Document must be a string",
			INVALID_PAGINATION: "Invalid pagination",
			PAGINATION_MUST_BE_STRING: "Pagination must be a string",
			INVALID_COUNT: "Invalid count",
			COUNT_MUST_BE_STRING: "Count must be a string",
			INVALID_GROUPBY: "Invalid groupBy",
			INVALID_COMBINATION: "Invalid combination",
		},
		COMMON: {
			INTERNAL_SERVER_ERROR: "Internal server error",
			VALIDATION_ERROR: "Validation error",
			NOT_FOUND: "Resource not found",
			UNAUTHORIZED: "Unauthorized access",
			NO_UPDATE_FIELDS: "No fields provided for update",
		},
		FACILITY: {
			VALIDATION_FAILED: "Facility validation failed",
			INVALID_ID_FORMAT: "Invalid facility ID format",
			NOT_FOUND: "Facility not found",
			CREATE_FAILED: "Error creating facility",
			UPDATE_FAILED: "Error updating facility",
			DELETE_FAILED: "Error deleting facility",
			GET_FAILED: "Error getting facility",
			GET_ALL_FAILED: "Error getting facilitys",
			ERROR_GETTING: "Error getting facility",
			ERROR_UPDATING: "Error updating facility",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		FACILITYTYPE: {
			VALIDATION_FAILED: "FacilityType validation failed",
			INVALID_ID_FORMAT: "Invalid facilitytype ID format",
			NOT_FOUND: "FacilityType not found",
			CREATE_FAILED: "Error creating facilitytype",
			UPDATE_FAILED: "Error updating facilitytype",
			DELETE_FAILED: "Error deleting facilitytype",
			GET_FAILED: "Error getting facilitytype",
			GET_ALL_FAILED: "Error getting facilitytypes",
			ERROR_GETTING: "Error getting facilitytype",
			ERROR_UPDATING: "Error updating facilitytype",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		RATETYPE: {
			VALIDATION_FAILED: "RateType validation failed",
			INVALID_ID_FORMAT: "Invalid ratetype ID format",
			NOT_FOUND: "RateType not found",
			CREATE_FAILED: "Error creating ratetype",
			UPDATE_FAILED: "Error updating ratetype",
			DELETE_FAILED: "Error deleting ratetype",
			GET_FAILED: "Error getting ratetype",
			GET_ALL_FAILED: "Error getting ratetypes",
			ERROR_GETTING: "Error getting ratetype",
			ERROR_UPDATING: "Error updating ratetype",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		LOCATION: {
			VALIDATION_FAILED: "Location validation failed",
			INVALID_ID_FORMAT: "Invalid location ID format",
			NOT_FOUND: "Location not found",
			CREATE_FAILED: "Error creating location",
			UPDATE_FAILED: "Error updating location",
			DELETE_FAILED: "Error deleting location",
			GET_FAILED: "Error getting location",
			GET_ALL_FAILED: "Error getting locations",
			ERROR_GETTING: "Error getting location",
			ERROR_UPDATING: "Error updating location",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		RESERVATION: {
			VALIDATION_FAILED: "Reservation validation failed",
			INVALID_ID_FORMAT: "Invalid reservation ID format",
			NOT_FOUND: "Reservation not found",
			CREATE_FAILED: "Error creating reservation",
			UPDATE_FAILED: "Error updating reservation",
			DELETE_FAILED: "Error deleting reservation",
			GET_FAILED: "Error getting reservation",
			GET_ALL_FAILED: "Error getting reservations",
			ERROR_GETTING: "Error getting reservation",
			ERROR_UPDATING: "Error updating reservation",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
	},

	SUCCESS: {
		AUTH: {
			REGISTRATION_SUCCESSFUL: "Registration successful",
			LOGGED_IN_SUCCESSFULLY: "Logged in successfully",
			PASSWORD_UPDATED_SUCCESSFULLY: "Password updated successfully",
			USER_CREATED: "User created successfully",
			TOKEN_GENERATED: "Token generated successfully",
			ORGANIZATION_VERIFIED: "Organization verified successfully",
			USER_LOGGED_IN: "User logged in successfully",
		},
		TEMPLATE: {
			CREATED: "Template created successfully",
			UPDATED: "Template updated successfully",
			DELETED: "Template deleted successfully",
			RETRIEVED: "Template retrieved successfully",
			RETRIEVED_ALL: "Templates retrieved successfully",
			GETTING_BY_ID: "Getting template by ID",
		},
		COMMON: {
			OPERATION_SUCCESSFUL: "Operation completed successfully",
		},
		FACILITY: {
			CREATED: "Facility created successfully",
			UPDATED: "Facility updated successfully",
			DELETED: "Facility deleted successfully",
			RETRIEVED: "Facility retrieved successfully",
			RETRIEVED_ALL: "Facilitys retrieved successfully",
			GETTING_BY_ID: "Getting facility by ID",
		},
		FACILITYTYPE: {
			CREATED: "FacilityType created successfully",
			UPDATED: "FacilityType updated successfully",
			DELETED: "FacilityType deleted successfully",
			RETRIEVED: "FacilityType retrieved successfully",
			RETRIEVED_ALL: "FacilityTypes retrieved successfully",
			GETTING_BY_ID: "Getting facilitytype by ID",
		},
		RATETYPE: {
			CREATED: "RateType created successfully",
			UPDATED: "RateType updated successfully",
			DELETED: "RateType deleted successfully",
			RETRIEVED: "RateType retrieved successfully",
			RETRIEVED_ALL: "RateTypes retrieved successfully",
			GETTING_BY_ID: "Getting ratetype by ID",
		},
		LOCATION: {
			CREATED: "Location created successfully",
			UPDATED: "Location updated successfully",
			DELETED: "Location deleted successfully",
			RETRIEVED: "Location retrieved successfully",
			RETRIEVED_ALL: "Locations retrieved successfully",
			GETTING_BY_ID: "Getting location by ID",
		},
		RESERVATION: {
			CREATED: "Reservation created successfully",
			UPDATED: "Reservation updated successfully",
			DELETED: "Reservation deleted successfully",
			RETRIEVED: "Reservation retrieved successfully",
			RETRIEVED_ALL: "Reservations retrieved successfully",
			GETTING_BY_ID: "Getting reservation by ID",
		},
	},

	ACTIVITY_LOG: {
		RESERVATION: {
			ACTIONS: {
				CREATE_RESERVATION: "CREATE_RESERVATION",
				GET_ALL_RESERVATION: "GET_ALL_RESERVATION",
				GET_RESERVATION: "GET_RESERVATION",
				UPDATE_RESERVATION: "UPDATE_RESERVATION",
				DELETE_RESERVATION: "DELETE_RESERVATION",
			},
			DESCRIPTIONS: {
				RESERVATION_CREATED: "Created new reservation",
				RESERVATION_UPDATED: "Updated reservation",
				RESERVATION_DELETED: "Deleted reservation",
				RESERVATION_RETRIEVED: "Retrieved reservation details",
				RESERVATIONS_RETRIEVED: "Retrieved reservation list",
			},
			PAGES: {
				RESERVATION_CREATION: "Reservation Creation",
				RESERVATION_UPDATE: "Reservation Update",
				RESERVATION_DELETION: "Reservation Deletion",
				RESERVATION_DETAILS: "Reservation Details",
				RESERVATION_LIST: "Reservation List",
			},
		},
		LOCATION: {
			ACTIONS: {
				CREATE_LOCATION: "CREATE_LOCATION",
				GET_ALL_LOCATION: "GET_ALL_LOCATION",
				GET_LOCATION: "GET_LOCATION",
				UPDATE_LOCATION: "UPDATE_LOCATION",
				DELETE_LOCATION: "DELETE_LOCATION",
			},
			DESCRIPTIONS: {
				LOCATION_CREATED: "Created new location",
				LOCATION_UPDATED: "Updated location",
				LOCATION_DELETED: "Deleted location",
				LOCATION_RETRIEVED: "Retrieved location details",
				LOCATIONS_RETRIEVED: "Retrieved location list",
			},
			PAGES: {
				LOCATION_CREATION: "Location Creation",
				LOCATION_UPDATE: "Location Update",
				LOCATION_DELETION: "Location Deletion",
				LOCATION_DETAILS: "Location Details",
				LOCATION_LIST: "Location List",
			},
		},
		RATETYPE: {
			ACTIONS: {
				CREATE_RATETYPE: "CREATE_RATETYPE",
				GET_ALL_RATETYPE: "GET_ALL_RATETYPE",
				GET_RATETYPE: "GET_RATETYPE",
				UPDATE_RATETYPE: "UPDATE_RATETYPE",
				DELETE_RATETYPE: "DELETE_RATETYPE",
			},
			DESCRIPTIONS: {
				RATETYPE_CREATED: "Created new ratetype",
				RATETYPE_UPDATED: "Updated ratetype",
				RATETYPE_DELETED: "Deleted ratetype",
				RATETYPE_RETRIEVED: "Retrieved ratetype details",
				RATETYPES_RETRIEVED: "Retrieved ratetype list",
			},
			PAGES: {
				RATETYPE_CREATION: "RateType Creation",
				RATETYPE_UPDATE: "RateType Update",
				RATETYPE_DELETION: "RateType Deletion",
				RATETYPE_DETAILS: "RateType Details",
				RATETYPE_LIST: "RateType List",
			},
		},
		FACILITYTYPE: {
			ACTIONS: {
				CREATE_FACILITYTYPE: "CREATE_FACILITYTYPE",
				GET_ALL_FACILITYTYPE: "GET_ALL_FACILITYTYPE",
				GET_FACILITYTYPE: "GET_FACILITYTYPE",
				UPDATE_FACILITYTYPE: "UPDATE_FACILITYTYPE",
				DELETE_FACILITYTYPE: "DELETE_FACILITYTYPE",
			},
			DESCRIPTIONS: {
				FACILITYTYPE_CREATED: "Created new facilitytype",
				FACILITYTYPE_UPDATED: "Updated facilitytype",
				FACILITYTYPE_DELETED: "Deleted facilitytype",
				FACILITYTYPE_RETRIEVED: "Retrieved facilitytype details",
				FACILITYTYPES_RETRIEVED: "Retrieved facilitytype list",
			},
			PAGES: {
				FACILITYTYPE_CREATION: "FacilityType Creation",
				FACILITYTYPE_UPDATE: "FacilityType Update",
				FACILITYTYPE_DELETION: "FacilityType Deletion",
				FACILITYTYPE_DETAILS: "FacilityType Details",
				FACILITYTYPE_LIST: "FacilityType List",
			},
		},
		FACILITY: {
			ACTIONS: {
				CREATE_FACILITY: "CREATE_FACILITY",
				GET_ALL_FACILITY: "GET_ALL_FACILITY",
				GET_FACILITY: "GET_FACILITY",
				UPDATE_FACILITY: "UPDATE_FACILITY",
				DELETE_FACILITY: "DELETE_FACILITY",
			},
			DESCRIPTIONS: {
				FACILITY_CREATED: "Created new facility",
				FACILITY_UPDATED: "Updated facility",
				FACILITY_DELETED: "Deleted facility",
				FACILITY_RETRIEVED: "Retrieved facility details",
				FACILITYS_RETRIEVED: "Retrieved facility list",
			},
			PAGES: {
				FACILITY_CREATION: "Facility Creation",
				FACILITY_UPDATE: "Facility Update",
				FACILITY_DELETION: "Facility Deletion",
				FACILITY_DETAILS: "Facility Details",
				FACILITY_LIST: "Facility List",
			},
		},
		TEMPLATE: {
			ACTIONS: {
				CREATE_TEMPLATE: "CREATE_TEMPLATE",
				GET_ALL_TEMPLATE: "GET_ALL_TEMPLATE",
				GET_TEMPLATE: "GET_TEMPLATE",
				UPDATE_TEMPLATE: "UPDATE_TEMPLATE",
				DELETE_TEMPLATE: "DELETE_TEMPLATE",
				USER_LOGIN: "USER_LOGIN",
				USER_LOGOUT: "USER_LOGOUT",
				USER_REGISTRATION: "USER_REGISTRATION",
				PASSWORD_UPDATE: "PASSWORD_UPDATE",
			},
			DESCRIPTIONS: {
				TEMPLATE_CREATED: "Created new template",
				TEMPLATE_UPDATED: "Updated template",
				TEMPLATE_DELETED: "Deleted template",
				TEMPLATE_RETRIEVED: "Retrieved template details",
				TEMPLATES_RETRIEVED: "Retrieved template list",
				USER_LOGGED_IN: "User logged in",
				USER_LOGGED_OUT: "User logged out",
				USER_REGISTERED: "User registered",
				PASSWORD_CHANGED: "Password changed",
			},
			PAGES: {
				TEMPLATE_CREATION: "Template Creation",
				TEMPLATE_UPDATE: "Template Update",
				TEMPLATE_DELETION: "Template Deletion",
				TEMPLATE_DETAILS: "Template Details",
				TEMPLATE_LIST: "Template List",
				USER_LOGIN: "User Login",
				USER_REGISTRATION: "User Registration",
				PASSWORD_CHANGE: "Password Change",
			},
		},
	},

	AUDIT_LOG: {
		ACTIONS: {
			CREATE: "CREATE",
			READ: "READ",
			UPDATE: "UPDATE",
			DELETE: "DELETE",
			LOGIN: "LOGIN",
			LOGOUT: "LOGOUT",
			REGISTER: "REGISTER",
		},
		RESOURCES: {
			TEMPLATE: "templates",
			USERS: "users",
			ORGANIZATIONS: "organizations",
			AUTH: "auth",
			FACILITY: "facility",
			FACILITYTYPE: "facilitytype",
			RATETYPE: "ratetype",
			LOCATION: "location",
			RESERVATION: "reservation",
		},
		SEVERITY: {
			LOW: "LOW" as const,
			MEDIUM: "MEDIUM" as const,
			HIGH: "HIGH" as const,
			CRITICAL: "CRITICAL" as const,
		},
		ENTITY_TYPES: {
			TEMPLATE: "template",
			USER: "user",
			ORGANIZATION: "organization",
			FACILITY: "facility",
			FACILITYTYPE: "facilitytype",
			RATETYPE: "ratetype",
			LOCATION: "location",
			RESERVATION: "reservation",
		},
		FACILITY: {
			DESCRIPTIONS: {
				FACILITY_CREATED: "Created new facility",
				FACILITY_UPDATED: "Updated facility",
				FACILITY_DELETED: "Deleted facility",
			},
		},
		FACILITYTYPE: {
			DESCRIPTIONS: {
				FACILITYTYPE_CREATED: "Created new facilitytype",
				FACILITYTYPE_UPDATED: "Updated facilitytype",
				FACILITYTYPE_DELETED: "Deleted facilitytype",
			},
		},
		RATETYPE: {
			DESCRIPTIONS: {
				RATETYPE_CREATED: "Created new ratetype",
				RATETYPE_UPDATED: "Updated ratetype",
				RATETYPE_DELETED: "Deleted ratetype",
			},
		},
		LOCATION: {
			DESCRIPTIONS: {
				LOCATION_CREATED: "Created new location",
				LOCATION_UPDATED: "Updated location",
				LOCATION_DELETED: "Deleted location",
			},
		},
		RESERVATION: {
			DESCRIPTIONS: {
				RESERVATION_CREATED: "Created new reservation",
				RESERVATION_UPDATED: "Updated reservation",
				RESERVATION_DELETED: "Deleted reservation",
			},
		},





		TEMPLATE: {
			DESCRIPTIONS: {
				TEMPLATE_CREATED: "Created new template",
				TEMPLATE_UPDATED: "Updated template",
				TEMPLATE_DELETED: "Deleted template",
				USER_CREATED: "Created new user",
				USER_UPDATED: "Updated user",
				USER_DELETED: "Deleted user",
				USER_LOGGED_IN: "User logged in",
				USER_LOGGED_OUT: "User logged out",
			},
		},
	},
};
