export const config = {
	ERROR: {
		AUTH: {
			UNAUTHORIZED: "Unauthorized",
			INVALID_TOKEN: "Invalid token",
			REGISTRATION_VALIDATION_FAILED: "Registration validation failed",
			LOGIN_VALIDATION_FAILED: "Login validation failed",
			PASSWORD_UPDATE_VALIDATION_FAILED: "Password update validation failed",
			FIRST_NAME_LAST_NAME_REQUIRED: "First name and last name are required",
			INVALID_ORGANIZATION_ID_FORMAT: "Invalid organization ID format",
			ORGANIZATION_NOT_FOUND: "Organization not found",
			USER_ALREADY_EXISTS: "User already exists",
			ERROR_DURING_REGISTRATION: "Error during registration",
			INVALID_CREDENTIALS: "Invalid credentials",
			ERROR_DURING_LOGIN: "Error during login",
			USER_ID_PASSWORD_REQUIRED: "User ID and new password are required",
			PASSWORD_MIN_LENGTH: "Password must be at least 6 characters long",
			ERROR_UPDATING_PASSWORD: "Error updating password",
			USER_NOT_FOUND: "User not found",
			FAILED_TO_CREATE_OR_FIND_PERSON: "Failed to create or find person",
		},
		TEMPLATE: {
			VALIDATION_FAILED: "Template validation failed",
			INVALID_ID_FORMAT: "Invalid template ID format",
			NOT_FOUND: "Template not found",
			CREATE_FAILED: "Error creating template",
			UPDATE_FAILED: "Error updating template",
			DELETE_FAILED: "Error deleting template",
			GET_FAILED: "Error getting template",
			GET_ALL_FAILED: "Error getting templates",
			ERROR_GETTING: "Error getting template",
			ERROR_UPDATING: "Error updating template",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		QUERY_PARAMS: {
			MISSING_ID: "ID parameter is required",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate must be a string",
			INVALID_PAGE: "Invalid page",
			INVALID_LIMIT: "Invalid limit",
			INVALID_ORDER: "Invalid order",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
			INVALID_SORT: "Invalid sort",
			SORT_MUST_BE_STRING: "Sort must be a string",
			INVALID_FILTER: "Invalid filter",
			FILTER_MUST_BE_STRING: "Filter must be a string",
			INVALID_QUERY: "Invalid query",
			QUERY_MUST_BE_STRING: "Query must be a string",
			INVALID_DOCUMENT: "Invalid document",
			DOCUMENT_MUST_BE_STRING: "Document must be a string",
			INVALID_PAGINATION: "Invalid pagination",
			PAGINATION_MUST_BE_STRING: "Pagination must be a string",
			INVALID_COUNT: "Invalid count",
			COUNT_MUST_BE_STRING: "Count must be a string",
			INVALID_GROUPBY: "Invalid groupBy",
			INVALID_COMBINATION: "Invalid combination",
		},
		COMMON: {
			INTERNAL_SERVER_ERROR: "Internal server error",
			VALIDATION_ERROR: "Validation error",
			NOT_FOUND: "Resource not found",
			UNAUTHORIZED: "Unauthorized access",
			NO_UPDATE_FIELDS: "No fields provided for update",
		},
		FACILITY: {
			VALIDATION_FAILED: "Facility validation failed",
			INVALID_ID_FORMAT: "Invalid facility ID format",
			NOT_FOUND: "Facility not found",
			CREATE_FAILED: "Error creating facility",
			UPDATE_FAILED: "Error updating facility",
			DELETE_FAILED: "Error deleting facility",
			GET_FAILED: "Error getting facility",
			GET_ALL_FAILED: "Error getting facilitys",
			ERROR_GETTING: "Error getting facility",
			ERROR_UPDATING: "Error updating facility",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
	},

	SUCCESS: {
		AUTH: {
			REGISTRATION_SUCCESSFUL: "Registration successful",
			LOGGED_IN_SUCCESSFULLY: "Logged in successfully",
			PASSWORD_UPDATED_SUCCESSFULLY: "Password updated successfully",
			USER_CREATED: "User created successfully",
			TOKEN_GENERATED: "Token generated successfully",
			ORGANIZATION_VERIFIED: "Organization verified successfully",
			USER_LOGGED_IN: "User logged in successfully",
		},
		TEMPLATE: {
			CREATED: "Template created successfully",
			UPDATED: "Template updated successfully",
			DELETED: "Template deleted successfully",
			RETRIEVED: "Template retrieved successfully",
			RETRIEVED_ALL: "Templates retrieved successfully",
			GETTING_BY_ID: "Getting template by ID",
		},
		COMMON: {
			OPERATION_SUCCESSFUL: "Operation completed successfully",
		},
		FACILITY: {
			CREATED: "Facility created successfully",
			UPDATED: "Facility updated successfully",
			DELETED: "Facility deleted successfully",
			RETRIEVED: "Facility retrieved successfully",
			RETRIEVED_ALL: "Facilitys retrieved successfully",
			GETTING_BY_ID: "Getting facility by ID",
		},
	},

	ACTIVITY_LOG: {
		FACILITY: {
			ACTIONS: {
				CREATE_FACILITY: "CREATE_FACILITY",
				GET_ALL_FACILITY: "GET_ALL_FACILITY",
				GET_FACILITY: "GET_FACILITY",
				UPDATE_FACILITY: "UPDATE_FACILITY",
				DELETE_FACILITY: "DELETE_FACILITY",
			},
			DESCRIPTIONS: {
				FACILITY_CREATED: "Created new facility",
				FACILITY_UPDATED: "Updated facility",
				FACILITY_DELETED: "Deleted facility",
				FACILITY_RETRIEVED: "Retrieved facility details",
				FACILITYS_RETRIEVED: "Retrieved facility list",
			},
			PAGES: {
				FACILITY_CREATION: "Facility Creation",
				FACILITY_UPDATE: "Facility Update",
				FACILITY_DELETION: "Facility Deletion",
				FACILITY_DETAILS: "Facility Details",
				FACILITY_LIST: "Facility List",
			},
		},
		TEMPLATE: {
			ACTIONS: {
				CREATE_TEMPLATE: "CREATE_TEMPLATE",
				GET_ALL_TEMPLATE: "GET_ALL_TEMPLATE",
				GET_TEMPLATE: "GET_TEMPLATE",
				UPDATE_TEMPLATE: "UPDATE_TEMPLATE",
				DELETE_TEMPLATE: "DELETE_TEMPLATE",
				USER_LOGIN: "USER_LOGIN",
				USER_LOGOUT: "USER_LOGOUT",
				USER_REGISTRATION: "USER_REGISTRATION",
				PASSWORD_UPDATE: "PASSWORD_UPDATE",
			},
			DESCRIPTIONS: {
				TEMPLATE_CREATED: "Created new template",
				TEMPLATE_UPDATED: "Updated template",
				TEMPLATE_DELETED: "Deleted template",
				TEMPLATE_RETRIEVED: "Retrieved template details",
				TEMPLATES_RETRIEVED: "Retrieved template list",
				USER_LOGGED_IN: "User logged in",
				USER_LOGGED_OUT: "User logged out",
				USER_REGISTERED: "User registered",
				PASSWORD_CHANGED: "Password changed",
			},
			PAGES: {
				TEMPLATE_CREATION: "Template Creation",
				TEMPLATE_UPDATE: "Template Update",
				TEMPLATE_DELETION: "Template Deletion",
				TEMPLATE_DETAILS: "Template Details",
				TEMPLATE_LIST: "Template List",
				USER_LOGIN: "User Login",
				USER_REGISTRATION: "User Registration",
				PASSWORD_CHANGE: "Password Change",
			},
		},
	},

	AUDIT_LOG: {
		ACTIONS: {
			CREATE: "CREATE",
			READ: "READ",
			UPDATE: "UPDATE",
			DELETE: "DELETE",
			LOGIN: "LOGIN",
			LOGOUT: "LOGOUT",
			REGISTER: "REGISTER",
		},
		RESOURCES: {
			TEMPLATE: "templates",
			USERS: "users",
			ORGANIZATIONS: "organizations",
			AUTH: "auth",
			FACILITY: "facility",
		},
		SEVERITY: {
			LOW: "LOW" as const,
			MEDIUM: "MEDIUM" as const,
			HIGH: "HIGH" as const,
			CRITICAL: "CRITICAL" as const,
		},
		ENTITY_TYPES: {
			TEMPLATE: "template",
			USER: "user",
			ORGANIZATION: "organization",
			FACILITY: "facility",
		},
		FACILITY: {
			DESCRIPTIONS: {
				FACILITY_CREATED: "Created new facility",
				FACILITY_UPDATED: "Updated facility",
				FACILITY_DELETED: "Deleted facility",
			},
		},

		TEMPLATE: {
			DESCRIPTIONS: {
				TEMPLATE_CREATED: "Created new template",
				TEMPLATE_UPDATED: "Updated template",
				TEMPLATE_DELETED: "Deleted template",
				USER_CREATED: "Created new user",
				USER_UPDATED: "Updated user",
				USER_DELETED: "Deleted user",
				USER_LOGGED_IN: "User logged in",
				USER_LOGGED_OUT: "User logged out",
			},
		},
	},
};
