name: Deploy to Heroku

on:
  push:
    branches:
      - develop  # Trigger on push to develop branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "reservation-api-dev"
          heroku_email: "1bis.solutions.tech@gmail.com"
          appdir: "."

